name: Test, Build and Push to ECR
on:
  push
env:
  AWS_REGION : "eu-central-1"
  REPOSITORY: secudoc
permissions: write-all # change this to granular permissions
  # id-token: write   # This is required for requesting the JWT
  # contents: read    # This is required for actions/checkout
  
jobs:
  Unit_Test:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: cargo test >> $GITHUB_STEP_SUMMARY

      - name: fail if exit code is not 0
        shell: bash
        run: if [ $? -ne 0 ]; then exit 1; fi