name: Test, Build and Push to ECR
on:
  push
env:
  AWS_REGION : "eu-central-1"
  REPOSITORY : "rust"
permissions: write-all # change this to granular permissions
  # id-token: write   # This is required for requesting the JWT
  # contents: read    # This is required for actions/checkout
  
jobs:
  Unit_Test:
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: cargo test >> $GITHUB_STEP_SUMMARY

      - name: fail if exit code is not 0
        shell: bash
        run: if [ $? -ne 0 ]; then exit 1; fi

  Build_Docker_Image:
    timeout-minutes: 4
    needs: Unit_Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::060595330994:role/github_actions
          aws-region: ${{ env.AWS_REGION }}
          mask-aws-account-id: 'false'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ env.REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          tags: ${{ env.REGISTRY }}/${{ env.REPOSITORY }}:${{ env.IMAGE_TAG }}
          push: true
          provenance: false